# Generated by Django 4.2.1 on 2023-05-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('bio', models.TextField()),
                ('profile_photo_path', models.TextField()),
                ('link_count', models.IntegerField()),
                ('background', models.CharField(max_length=25)),
            ],
        ),
    ]
