# Generated by Django 4.2.1 on 2023-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
