# Generated by Django 4.2.1 on 2023-05-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_remove_user_id_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id_card', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id_ownership', models.AutoField(primary_key=True, serialize=False)),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.card')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.user')),
            ],
        ),
    ]
