# Generated by Django 4.2.1 on 2023-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
